### ISSUE TITLE
Republish as embree?

### ISSUE THREAD

**Issue by newpavlov** [Twinklebear/embree-rs#5]
Of course, assuming @tilpner will transfer ownership of the crate to you.

**Comment by tilpner** [comment]
Of course! I've invited @Twinklebear to be an owner of the `embree` crate. After they've accepted, feel free to remove me as an owner and publish.

**Comment by Twinklebear** [comment]
Thanks @tilpner ! We can move the create to `embree`, since (as far as I remember) the `-rs` suffix is more for plain wrapper crates over a C API. My goal here when I have time is to be more Rust-style/higher level.

I've updated the libs and examples now, and will let CI run through to check that things are building ok, then will push the crate and close this.

**Comment by newpavlov** [comment]
Also note that a very common convention for wrapper crates is to have a thin `*-sys` crate, which exposes raw C functions and handles linking, while the main crate implements safe abstractions on top of it.

**Comment by Twinklebear** [comment]
Ah that's right, I forgot the `-sys` convention. If it would be useful I could actually push the sys bindings and build script separately to make an `embree-sys` crate. I have to make this anyways to in this crate to provide the base for it

**Comment by Twinklebear** [comment]
I just pushed the crate up as `embree` 🎉

**Comment by tilpner** [comment]
Did you forget to remove me as a crate owner, or did you try and it failed?

**Comment by Twinklebear** [comment]
Oh I didn't do that yet actually, let me try now.

**Comment by Twinklebear** [comment]
Ok all set! 👍  Thanks again @tilpner
